// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Solicitude struct {
	ID       int64
	Pasajero string
	Chofer   sql.NullString
	Origen   string
	Destino  string
	Estado   string
	Creadoen sql.NullTime
}

type Usuario struct {
	ID        int64
	Nombre    string
	Rol       string
	Matricula string
}
