// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const actualizarSolicitud = `-- name: ActualizarSolicitud :one
UPDATE solicitudes
SET estado = ?, chofer = COALESCE(?, chofer)
WHERE id = ?
RETURNING id, pasajero, chofer, origen, destino, estado, creadoen
`

type ActualizarSolicitudParams struct {
	Estado string
	Chofer sql.NullString
	ID     int64
}

func (q *Queries) ActualizarSolicitud(ctx context.Context, arg ActualizarSolicitudParams) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitud, arg.Estado, arg.Chofer, arg.ID)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.Pasajero,
		&i.Chofer,
		&i.Origen,
		&i.Destino,
		&i.Estado,
		&i.Creadoen,
	)
	return i, err
}

const actualizarUsuario = `-- name: ActualizarUsuario :one
UPDATE usuarios
SET nombre = ?, rol = ?, matricula = ?
WHERE id = ?
RETURNING id, nombre, rol, matricula
`

type ActualizarUsuarioParams struct {
	Nombre    string
	Rol       string
	Matricula string
	ID        int64
}

func (q *Queries) ActualizarUsuario(ctx context.Context, arg ActualizarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, actualizarUsuario,
		arg.Nombre,
		arg.Rol,
		arg.Matricula,
		arg.ID,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Rol,
		&i.Matricula,
	)
	return i, err
}

const asignarChofer = `-- name: AsignarChofer :one
UPDATE solicitudes
SET chofer = ?
WHERE id = ?
RETURNING id, pasajero, chofer, origen, destino, estado, creadoen
`

type AsignarChoferParams struct {
	Chofer sql.NullString
	ID     int64
}

func (q *Queries) AsignarChofer(ctx context.Context, arg AsignarChoferParams) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, asignarChofer, arg.Chofer, arg.ID)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.Pasajero,
		&i.Chofer,
		&i.Origen,
		&i.Destino,
		&i.Estado,
		&i.Creadoen,
	)
	return i, err
}

const borrarSolicitud = `-- name: BorrarSolicitud :execrows
DELETE FROM solicitudes WHERE id = ?
`

func (q *Queries) BorrarSolicitud(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitud, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarUsuario = `-- name: BorrarUsuario :execrows
DELETE FROM usuarios WHERE id = ?
`

func (q *Queries) BorrarUsuario(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarUsuario, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarSolicitudPorID = `-- name: BuscarSolicitudPorID :one
SELECT id, pasajero, chofer, origen, destino, estado, creadoen FROM solicitudes
WHERE id = ?
`

func (q *Queries) BuscarSolicitudPorID(ctx context.Context, id int64) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitudPorID, id)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.Pasajero,
		&i.Chofer,
		&i.Origen,
		&i.Destino,
		&i.Estado,
		&i.Creadoen,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, nombre, rol, matricula FROM usuarios
WHERE id = ?
`

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, buscarUsuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Rol,
		&i.Matricula,
	)
	return i, err
}

const crearSolicitud = `-- name: CrearSolicitud :one
INSERT INTO solicitudes (pasajero, origen, destino, estado)
VALUES (?, ?, ?, 'pendiente')
RETURNING id, pasajero, chofer, origen, destino, estado, creadoen
`

type CrearSolicitudParams struct {
	Pasajero string
	Origen   string
	Destino  string
}

func (q *Queries) CrearSolicitud(ctx context.Context, arg CrearSolicitudParams) (Solicitude, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitud, arg.Pasajero, arg.Origen, arg.Destino)
	var i Solicitude
	err := row.Scan(
		&i.ID,
		&i.Pasajero,
		&i.Chofer,
		&i.Origen,
		&i.Destino,
		&i.Estado,
		&i.Creadoen,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one
INSERT INTO usuarios (nombre, rol, matricula)
Values (?, ?, ?)
RETURNING id, nombre, rol, matricula
`

type CrearUsuarioParams struct {
	Nombre    string
	Rol       string
	Matricula string
}

func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.Nombre, arg.Rol, arg.Matricula)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Rol,
		&i.Matricula,
	)
	return i, err
}

const listarSolicitudes = `-- name: ListarSolicitudes :many

SELECT id, pasajero, chofer, origen, destino, estado, creadoen FROM solicitudes
`

// =========== SOLICITUDES =================
func (q *Queries) ListarSolicitudes(ctx context.Context) ([]Solicitude, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitudes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solicitude
	for rows.Next() {
		var i Solicitude
		if err := rows.Scan(
			&i.ID,
			&i.Pasajero,
			&i.Chofer,
			&i.Origen,
			&i.Destino,
			&i.Estado,
			&i.Creadoen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuario = `-- name: ListarUsuario :many

SELECT id, nombre, rol, matricula FROM usuarios
`

// ========= USUARIOS =======================
func (q *Queries) ListarUsuario(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listarUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Rol,
			&i.Matricula,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
